export const gloryStateData = [
  {
    2022: {
      State_Medals: [
        // {
        //   no_of_users: 1,
        //   Medals: 1,
        //   Gold: 0,
        //   Silver: 0,
        //   Bronze: 1,
        //   Cashes: 1,
        //   winnings: 57364.5,
        //   state: "Null",
        // },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 1,
          Silver: 0,
          Bronze: 0,
          Cashes: 4,
          winnings: 186518.48,
          state: "Arunachal Pradesh",
        },
        {
          no_of_users: 6,
          Medals: 7,
          Gold: 2,
          Silver: 1,
          Bronze: 4,
          Cashes: 75,
          winnings: 1194041.48,
          state: "Bihar",
        },
        {
          no_of_users: 2,
          Medals: 2,
          Gold: 1,
          Silver: 0,
          Bronze: 1,
          Cashes: 23,
          winnings: 601093.48,
          state: "Chhattisgarh",
        },
        {
          no_of_users: 2,
          Medals: 2,
          Gold: 0,
          Silver: 0,
          Bronze: 2,
          Cashes: 43,
          winnings: 449372.689999999,
          state: "Delhi",
        },
        {
          no_of_users: 10,
          Medals: 12,
          Gold: 4,
          Silver: 3,
          Bronze: 5,
          Cashes: 179,
          winnings: 9891496.06999999,
          state: "Goa",
        },
        {
          no_of_users: 16,
          Medals: 21,
          Gold: 6,
          Silver: 8,
          Bronze: 7,
          Cashes: 313,
          winnings: 11804581.26,
          state: "Haryana",
        },
        {
          no_of_users: 1,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 22,
          winnings: 750657.9,
          state: "Himachal Pradesh",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 0,
          Silver: 0,
          Bronze: 1,
          Cashes: 12,
          winnings: 134045.84,
          state: "Jammu and Kashmir",
        },
        {
          no_of_users: 3,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 11,
          winnings: 4556434.24,
          state: "Jharkhand",
        },
        {
          no_of_users: 11,
          Medals: 12,
          Gold: 6,
          Silver: 4,
          Bronze: 2,
          Cashes: 118,
          winnings: 6113504.93,
          state: "Karnataka",
        },
        {
          no_of_users: 3,
          Medals: 5,
          Gold: 1,
          Silver: 3,
          Bronze: 1,
          Cashes: 53,
          winnings: 1592535.64,
          state: "Madhya Pradesh",
        },
        {
          no_of_users: 40,
          Medals: 50,
          Gold: 15,
          Silver: 22,
          Bronze: 13,
          Cashes: 694,
          winnings: 21831698.28,
          state: "Maharashtra",
        },
        {
          no_of_users: 33,
          Medals: 43,
          Gold: 14,
          Silver: 10,
          Bronze: 19,
          Cashes: 573,
          winnings: 17736953.51,
          state: "New Delhi",
        },
        {
          no_of_users: 5,
          Medals: 8,
          Gold: 2,
          Silver: 5,
          Bronze: 1,
          Cashes: 79,
          winnings: 4280805.12,
          state: "Punjab",
        },
        {
          no_of_users: 19,
          Medals: 35,
          Gold: 15,
          Silver: 10,
          Bronze: 10,
          Cashes: 370,
          winnings: 12533168.2,
          state: "Rajasthan",
        },
        {
          no_of_users: 3,
          Medals: 3,
          Gold: 3,
          Silver: 0,
          Bronze: 0,
          Cashes: 32,
          winnings: 2300266.54,
          state: "Tamil Nadu",
        },
        {
          no_of_users: 25,
          Medals: 29,
          Gold: 6,
          Silver: 8,
          Bronze: 15,
          Cashes: 390,
          winnings: 12103428.6999999,
          state: "Uttar Pradesh",
        },
        {
          no_of_users: 2,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 65,
          winnings: 2564419.18,
          state: "Uttarakhand",
        },
        {
          no_of_users: 9,
          Medals: 11,
          Gold: 5,
          Silver: 4,
          Bronze: 2,
          Cashes: 107,
          winnings: 4560340.49999999,
          state: "West Bengal",
        },
      ],
      State_Winnings: [
        {
          no_of_users: 40,
          Medals: 50,
          Gold: 15,
          Silver: 22,
          Bronze: 13,
          Cashes: 694,
          winnings: 21831698.28,
          state: "Maharashtra",
        },
        {
          no_of_users: 33,
          Medals: 43,
          Gold: 14,
          Silver: 10,
          Bronze: 19,
          Cashes: 573,
          winnings: 17736953.51,
          state: "New Delhi",
        },
        {
          no_of_users: 19,
          Medals: 35,
          Gold: 15,
          Silver: 10,
          Bronze: 10,
          Cashes: 370,
          winnings: 12533168.2,
          state: "Rajasthan",
        },
        {
          no_of_users: 25,
          Medals: 29,
          Gold: 6,
          Silver: 8,
          Bronze: 15,
          Cashes: 390,
          winnings: 12103428.6999999,
          state: "Uttar Pradesh",
        },
        {
          no_of_users: 16,
          Medals: 21,
          Gold: 6,
          Silver: 8,
          Bronze: 7,
          Cashes: 313,
          winnings: 11804581.26,
          state: "Haryana",
        },
        {
          no_of_users: 10,
          Medals: 12,
          Gold: 4,
          Silver: 3,
          Bronze: 5,
          Cashes: 179,
          winnings: 9891496.06999999,
          state: "Goa",
        },
        {
          no_of_users: 11,
          Medals: 12,
          Gold: 6,
          Silver: 4,
          Bronze: 2,
          Cashes: 118,
          winnings: 6113504.93,
          state: "Karnataka",
        },
        {
          no_of_users: 9,
          Medals: 11,
          Gold: 5,
          Silver: 4,
          Bronze: 2,
          Cashes: 107,
          winnings: 4560340.49999999,
          state: "West Bengal",
        },
        {
          no_of_users: 3,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 11,
          winnings: 4556434.24,
          state: "Jharkhand",
        },
        {
          no_of_users: 5,
          Medals: 8,
          Gold: 2,
          Silver: 5,
          Bronze: 1,
          Cashes: 79,
          winnings: 4280805.12,
          state: "Punjab",
        },
        {
          no_of_users: 2,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 65,
          winnings: 2564419.18,
          state: "Uttarakhand",
        },
        {
          no_of_users: 3,
          Medals: 3,
          Gold: 3,
          Silver: 0,
          Bronze: 0,
          Cashes: 32,
          winnings: 2300266.54,
          state: "Tamil Nadu",
        },
        {
          no_of_users: 3,
          Medals: 5,
          Gold: 1,
          Silver: 3,
          Bronze: 1,
          Cashes: 53,
          winnings: 1592535.64,
          state: "Madhya Pradesh",
        },
        {
          no_of_users: 6,
          Medals: 7,
          Gold: 2,
          Silver: 1,
          Bronze: 4,
          Cashes: 75,
          winnings: 1194041.48,
          state: "Bihar",
        },
        {
          no_of_users: 1,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 22,
          winnings: 750657.9,
          state: "Himachal Pradesh",
        },
        {
          no_of_users: 2,
          Medals: 2,
          Gold: 1,
          Silver: 0,
          Bronze: 1,
          Cashes: 23,
          winnings: 601093.48,
          state: "Chhattisgarh",
        },
        {
          no_of_users: 2,
          Medals: 2,
          Gold: 0,
          Silver: 0,
          Bronze: 2,
          Cashes: 43,
          winnings: 449372.689999999,
          state: "Delhi",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 1,
          Silver: 0,
          Bronze: 0,
          Cashes: 4,
          winnings: 186518.48,
          state: "Arunachal Pradesh",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 0,
          Silver: 0,
          Bronze: 1,
          Cashes: 12,
          winnings: 134045.84,
          state: "Jammu and Kashmir",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 0,
          Silver: 0,
          Bronze: 1,
          Cashes: 1,
          winnings: 57364.5,
          state: "Null",
        },
      ],
      State_Cashes: [
        {
          no_of_users: 40,
          Medals: 50,
          Gold: 15,
          Silver: 22,
          Bronze: 13,
          Cashes: 694,
          winnings: 21831698.28,
          state: "Maharashtra",
        },
        {
          no_of_users: 33,
          Medals: 43,
          Gold: 14,
          Silver: 10,
          Bronze: 19,
          Cashes: 573,
          winnings: 17736953.51,
          state: "New Delhi",
        },
        {
          no_of_users: 25,
          Medals: 29,
          Gold: 6,
          Silver: 8,
          Bronze: 15,
          Cashes: 390,
          winnings: 12103428.6999999,
          state: "Uttar Pradesh",
        },
        {
          no_of_users: 19,
          Medals: 35,
          Gold: 15,
          Silver: 10,
          Bronze: 10,
          Cashes: 370,
          winnings: 12533168.2,
          state: "Rajasthan",
        },
        {
          no_of_users: 16,
          Medals: 21,
          Gold: 6,
          Silver: 8,
          Bronze: 7,
          Cashes: 313,
          winnings: 11804581.26,
          state: "Haryana",
        },
        {
          no_of_users: 10,
          Medals: 12,
          Gold: 4,
          Silver: 3,
          Bronze: 5,
          Cashes: 179,
          winnings: 9891496.06999999,
          state: "Goa",
        },
        {
          no_of_users: 11,
          Medals: 12,
          Gold: 6,
          Silver: 4,
          Bronze: 2,
          Cashes: 118,
          winnings: 6113504.93,
          state: "Karnataka",
        },
        {
          no_of_users: 9,
          Medals: 11,
          Gold: 5,
          Silver: 4,
          Bronze: 2,
          Cashes: 107,
          winnings: 4560340.49999999,
          state: "West Bengal",
        },
        {
          no_of_users: 5,
          Medals: 8,
          Gold: 2,
          Silver: 5,
          Bronze: 1,
          Cashes: 79,
          winnings: 4280805.12,
          state: "Punjab",
        },
        {
          no_of_users: 6,
          Medals: 7,
          Gold: 2,
          Silver: 1,
          Bronze: 4,
          Cashes: 75,
          winnings: 1194041.48,
          state: "Bihar",
        },
        {
          no_of_users: 2,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 65,
          winnings: 2564419.18,
          state: "Uttarakhand",
        },
        {
          no_of_users: 3,
          Medals: 5,
          Gold: 1,
          Silver: 3,
          Bronze: 1,
          Cashes: 53,
          winnings: 1592535.64,
          state: "Madhya Pradesh",
        },
        {
          no_of_users: 2,
          Medals: 2,
          Gold: 0,
          Silver: 0,
          Bronze: 2,
          Cashes: 43,
          winnings: 449372.689999999,
          state: "Delhi",
        },
        {
          no_of_users: 3,
          Medals: 3,
          Gold: 3,
          Silver: 0,
          Bronze: 0,
          Cashes: 32,
          winnings: 2300266.54,
          state: "Tamil Nadu",
        },
        {
          no_of_users: 2,
          Medals: 2,
          Gold: 1,
          Silver: 0,
          Bronze: 1,
          Cashes: 23,
          winnings: 601093.48,
          state: "Chhattisgarh",
        },
        {
          no_of_users: 1,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 22,
          winnings: 750657.9,
          state: "Himachal Pradesh",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 0,
          Silver: 0,
          Bronze: 1,
          Cashes: 12,
          winnings: 134045.84,
          state: "Jammu and Kashmir",
        },
        {
          no_of_users: 3,
          Medals: 3,
          Gold: 1,
          Silver: 2,
          Bronze: 0,
          Cashes: 11,
          winnings: 4556434.24,
          state: "Jharkhand",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 1,
          Silver: 0,
          Bronze: 0,
          Cashes: 4,
          winnings: 186518.48,
          state: "Arunachal Pradesh",
        },
        {
          no_of_users: 1,
          Medals: 1,
          Gold: 0,
          Silver: 0,
          Bronze: 1,
          Cashes: 1,
          winnings: 57364.5,
          state: "Null",
        },
      ],
    },
  },
];
